### PR TITLE
Initial cgo support

### LINKED ISSUE #92: cgo not supported
Creating this repo as an example of my problem https://github.com/fzerorubigd/gb-bug (The source is from the https://bitbucket.org/liamstask/goose ) 

`gb build` was failed with this message 
```
github.com/go-sql-driver/mysql
github.com/kylelemons/go-gypsy/yaml
github.com/lib/pq/oid
github.com/mattn/go-sqlite3
github.com/ziutek/mymysql/mysql
Usage: pack op file.a [name....]
Where op is one of cprtx optionally followed by v for verbose output.
For compatibility with old Go build environments the op string grc is
accepted as a synonym for c.

For more information, run
        godoc cmd/pack
# /usr/lib/go/pkg/tool/linux_amd64/pack r /tmp/gb128619612/github.com/mattn/go-sqlite3.a
github.com/lib/pq
github.com/ziutek/mymysql/native
FATAL command "build" failed: exit status 2
```

For reproduce, simply clone my repo https://bitbucket.org/liamstask/goose, (clone, submodule update) and then `gb build` but with `go get` every thing is fine.

### PR DESCRIPTION
**Pull request by davecheney**
Fixes #92 

Initial cgo support, many things are missing, but basic cgo compilation works.

### CODE REVIEW

**Comment by davidkaya** [comment]
@davecheney Will this PR include support for the Build Constraints mentioned here: http://golang.org/pkg/go/build/?

**Comment by davecheney** [comment]
No, but build constraints should already be supported.

**Comment by davidkaya** [comment]
Oh, yea sorry, I thought I was getting that "cgo not supported" because of the build constraints.
One more question: Is there a ETA for the cgo support? 
Thanks and keep up the brilliant work (gb is really great!) :)

**Comment by davecheney** [comment]
> One more question: Is there a ETA for the cgo support?

As soon as humanly possible.

**Pull request merged**
