### PR TITLE
gb-vendor: Adds support for the -branch flag to the update command

### PR DESCRIPTION
**Pull request by dcarney**
First off, thanks for all the hard work on gb!  I'm enthusiastically converting projects over to use it.

This PR adds support for the `-branch` flag to `gb vendor update` command. The flag works just as it does when using `gb vendor fetch`.

This allows you to take a currently vendored dependency and update it to the HEAD revision of a branch other than `master`.

Currently, the only way to achieve this functionality is with:
`$ gb vendor delete github.com/foo/bar`
`$ gb vendor update -branch=bugfix github.com/foo/bar`

which seems a little unnecessary.

### CODE REVIEW

**Comment by davecheney** [comment]
Assigning to @davidkaya as he has some strong feelings on the matter.

**Comment by davecheney** [comment]
@dcarney can you please update alldocs.go, inside cmd/gb-vendor, do `go install`, then `go generate`, which should rebuild `alldocs.go`.

**Comment by davidkaya** [comment]
We agreed in #136 that we won't add `branch` to `gb update` and it should by default update to the HEAD of the branch saved in the Manifest file. If a user wants to switch to other branch then he should delete/fetch the repository. Because updating to other branch is no longer updating but it is changing version.

However you found a bug, which probably occurred when Dave refactored the `repo` package. Because it should not be `repo.Checkout("", "")`, it should checkout the branch specified in the manifest file.

In the beginning of the cycle, there should be `branch := d.Branch` and that branch should be checked out.

**Comment by davecheney** [comment]
@dcarney I defer to @davidkaya on this one, I think his explanation that if you want to switch branches you should delete/fetch; as this is effectively what update is doing.

Thanks for finding the bug, I'd appreciate it if one of you sent a PR to fix it.

I'll consider this issue closed when fetch/update is documented to explain the workflow we expect.

Thanks

Dave

**Comment by davecheney** [comment]
@dcarney #211 fixes the bug i introduced. If you're happy with our explanation of rejecting -branch on update then I can close this with an update to the documentation.

How does that sound ?

**Comment by dcarney** [comment]
Sounds good. Thanks for the explanation.

**Pull request closed without merging**
