### PR TITLE
Only match package from $PROJECT/src

### LINKED ISSUE #505: cmd/gb: refuse to build any package that is not rooted in $PROJECT/src
Because gb uses `go/build` package resolution can be fooled into building any package that is in scope. This should be prohibited.
```
zapf(/tmp/src) % gb build net/http
FATAL: command "build" failed: failed to resolve import path "net/http": cannot find package "golang.org/x/net/http2/hpack" in any of:
        /Users/dfc/go/src/golang.org/x/net/http2/hpack (from $GOROOT)
        /tmp/src/golang.org/x/net/http2/hpack (from $GOPATH)
        /tmp/vendor/src/golang.org/x/net/http2/hpack
```
Had this not been Go 1.6, this would have succeeded, and will probably succeed once the resolver refactorings land.

### PR DESCRIPTION
**Pull request by davecheney**
Fixes #505

Only packages matching $PROJECT/src/... will match package arguments or globs.

### CODE REVIEW

**Comment by sr** [comment]
:sparkling_heart: thanks for fixing this.

**Comment by sr** [comment]
Side effects, possibly unwanted, probably interesting to note regardless:

Prior to this change, I was able to vendor all "binaries", e.g. do

```
$ gb vendor fetch github.com/golang/protobuf
$ gb build github.com/golang/protobuf/protoc-gen-go
$ ls bin/protoc-gen-go
```

**Comment by davecheney** [comment]
@sr sorry that this broke your workflow. I think I made  promise to someone that I would let package resolution match both roots in `$PROJECT/src` and `$PROJECT/vendor/src`, i'll fix it this morning.

**Comment by davecheney** [comment]
@sr #555 should fix the problem, i've added some tests to make sure

**Pull request merged**
