### PR TITLE
Initial cross compilation support

### PR DESCRIPTION
**Pull request by davecheney**
Updates #31 
Updates #32 

- [x] runtime must always be present in the package graph, handle the case where a main package has no imports.
- [x] introduce gohostos/gohostarch and gotargetos/gotargetarch to Context
- [x] don't rebuild stdlib when GOOS=GOHOSTOS etc
- [x] when host and target do not match, place binaries in `$PROJECT/bin/$targetos/$targetarch`

### CODE REVIEW

**Comment by tianon** [comment]
BOOM! :metal:

**Comment by davecheney** [comment]
@tianon hold your horses, this is still ways from being done.

**Comment by tianon** [comment]
Heh, I figured, but I wanted to let you know the effort is definitely
appreciated! This is awesome. :heart:

**Comment by davecheney** [comment]
@tianon thanks mate!

**Comment by davecheney** [comment]
Things are looking good
```
FATAL unable to construct context: cross compilation from host linux/amd64 to target linux/arm not supported. See issue #31
lucky(~/src/hello) % env GOARCH=arm gb build -P 1 -f -F -dotfile=/tmp/t
runtime
errors
sync/atomic
math
unicode/utf8
sync
strconv
syscall
reflect
io
time
os
fmt
hello
lucky(~/src/hello) % file ../../bin/hello 
../../bin/hello: ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped
```
outfile

**Pull request merged**
