### PR TITLE
add service.v1 integration test

### PR DESCRIPTION
**Pull request by davecheney**

### CODE REVIEW

**Comment by davecheney** [comment]
Sigh - another thing that wercker doesn't support

**Comment by tianon** [comment]
If you'd be interested in trying Travis, I'd be willing to play with setting up a `.travis.yml` build matrix for you. :+1:

**Comment by davecheney** [comment]
Sure. Go for it.

**Comment by tianon** [comment]
:metal: will play! :heart:

**Comment by davecheney** [comment]
I used wercker because it gives pre commit testing. I don't know much about
travis, but pre commit testing is key.

**Comment by mmlb** [comment]
You can have precommit testing + travis if you throw in another tool/service in the mix: https://github.com/barosl/homu

**Comment by davecheney** [comment]
This is sounding less and less attractive ...

**Comment by mmlb** [comment]
:D

**Comment by tianon** [comment]
Heh, yeah, it doesn't fit your needs.  Perhaps I'll just play with werker
instead and see if I can help debug. :+1:

**Comment by davecheney** [comment]
I think the solution to the wercker problem is to start with a different
"box", one that is based on a more complete os image.

It's not a big deal, all those integration tests are in the repo any way,
even if they cannot all be run through CI directly.

**Pull request closed without merging**
