### PR TITLE
support ssh with bitbucket and private repos

### PR DESCRIPTION
**Pull request by sc0rp1us**
P.S. do not forget bring back vendor imports

```
diff --git a/cmd/gb-vendor/fetch.go b/cmd/gb-vendor/fetch.go
index ee818be..711f1dd 100644
--- a/cmd/gb-vendor/fetch.go
+++ b/cmd/gb-vendor/fetch.go
@@ -13,7 +13,7 @@ import (
        "github.com/constabulary/gb"
        "github.com/constabulary/gb/cmd"
        "github.com/constabulary/gb/fileutils"
-       "github.com/constabulary/gb/vendor"
+       "github.com/sc0rp1us/gb/vendor"
 )

```

### CODE REVIEW

**Comment by davecheney** [comment]
Thank you for your proposal. There are a few things to fix before I can review it.

1. please remove the .gitignore change, that is not relevant to this PR.
2. Pleaes rename the pr to describe what this change does, maybe something like "vendor: support ssh with bitbucket repos" (i'm not sure, I haven't reviewed the change yet)
3. Please fix the incorrect import path. If you have a fork of gb you should check it out in the original location, then change the remote to point to your fork.

Thanks

Dave

**Comment by mattias-lundell** [comment]
What is left before this can be considered for merge?

**Comment by davecheney** [comment]
I'm sorry I lost track of this. It looks like their are some test failures. I haven't looked into the specific failure.

**Comment by davecheney** [comment]
@mariokostelac @sc0rp1us Please raise an issue and include the lines "Fixes # NNN" in the PR description. Thanks.

**Comment by davecheney** [comment]
I'm sorry but we cannot change the probe order, `https` must be first otherwise people will be bombarded with requests to provide their ssh key's passphrase during normal probing.

**Comment by davecheney** [comment]
I'm going to close this PR for the moment. Please open an issue to discuss the implementation before proposing a code change. 

Thank you for your understanding.

**Pull request closed without merging**
