### PR TITLE
cmd: generate correct suffix for windows test binaries

### LINKED ISSUE #396: gb test: windows binaries should be ".test.exe", not ".exe.test"

### PR DESCRIPTION
**Pull request by davecheney**
Fixes #396
Closes #411

### CODE REVIEW

**Comment by tianon** [comment]
Nice! :+1:

**Comment by davecheney** [comment]
Sorry for stealing your thunder, I had an unexpected burst of motivation
last night

**Comment by tianon** [comment]
You feel free to keep stealing my thunder! :metal:

I want successful gb way more than my name in the commits. :heart:

**Pull request merged**
