### PR TITLE
Properly handle cflags presented from pkg-config

### LINKED ISSUE #114: cgo: github.com/andlabs/ui - #include <gtk/gtk.h> not found
this is on linux/amd64

```
[cryptix@higgs ~/devel/projx/vendor/src/github.com/andlabs/ui] git log -1
commit e34c561ed5bedeb180437ec165882b98d70d38c1
Author: Pietro Gagliardi <pietro10@mac.com>
Date:   Thu Apr 16 20:33:28 2015 -0400

    Split the rewrite into a new repository.
[cryptix@higgs ~/devel/projx/vendor/src/github.com/andlabs/ui] go build -v
_/home/cryptix/devel/projx/vendor/src/github.com/andlabs/ui
[cryptix@higgs ~/devel/projx/vendor/src/github.com/andlabs/ui] gb build .
In file included from /home/cryptix/devel/projx/vendor/src/github.com/andlabs/ui/area_unix.go:13:0:
gtk_unix.h:23:21: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
                     ^
compilation terminated.
FATAL command "build" failed: # /home/cryptix/gotip/pkg/tool/linux_amd64/cgo -objdir /tmp/gb298671284/github.com/andlabs -- -I /home/cryptix/devel/projx/vendor/src/github.com/andlabs/ui area_unix.go button_unix.go checkbox_unix.go common_unix.go container_unix.go control_unix.go dialog_unix.go group_unix.go image_unix.go label_unix.go progressbar_unix.go spinbox_unix.go tab_unix.go table_unix.go textbox_unix.go textfield_unix.go uitask_unix.go window_unix.go: exit status 2
```

### PR DESCRIPTION
**Pull request by davecheney**
Fixes handling of cflags returned by pkg-config.

Replaces #303 
Fixes #114

### CODE REVIEW

**Comment by davecheney** [comment]
@sheenobu could you please pull this branch and test it. I've tested it passes the intergration test for go-sdl2 with go 1.4 and go 1.5, but I cannot add the integration test for wercker as they don't have the sdl2 debs available.

**Comment by sheenobu** [comment]
@davecheney On it.

**Comment by sheenobu** [comment]
Both sqlite3 and go-sdl2 integration tests now run successfully.

**Comment by davecheney** [comment]
Thanks for your help, and the original repo. I think this closed a bunch of issues.

**Pull request merged**
