### PR TITLE
fix,test(vendor): vendor fetch fail with pkg name length == 1

### PR DESCRIPTION
**Pull request by krhubert**
fix vendor fetch validimport regexp.
create test for package name length equal 1.

### CODE REVIEW

**Comment by davecheney** [comment]
Please add fixes #203 and use https://github.com/cznic/b

**Comment by davecheney** [comment]
@krhubert did you mean to close this ? I can land the final edits to the PR if you like.

**Comment by krhubert** [comment]
Yep, I've created new one, sorry for confusing

**Comment by davecheney** [comment]
No worries.

**Pull request closed without merging**
