### PR TITLE
vendor: give better error when fetch fails on insecure report import (improvement 1)

### PR DESCRIPTION
**Pull request by hyper-carrot**
It will print `unable to determine remote metadata protocol: failed to access url "..."` when fetch fails on insecure report import, no matter what insecure is set or not.

### CODE REVIEW

**Comment by davecheney** [comment]
@hyper-carrot somehow this PR is broken, possibly your editor or environment has mangled the whitespace in the werker yaml file, although github cannot detect it.

**Comment by hyper-carrot** [comment]
@davecheney  But I don't have edited werker.yml, and I haven't found any difference.  I will try to fix.

**Comment by tianon** [comment]
Might just need a rebase against latest master. :)

- Tianon

**Comment by davecheney** [comment]
It's ok, i've replaced this PR with another.

**Pull request closed without merging**
