### PR TITLE
vendor: give better error when fetch fails on insecure report import

### LINKED ISSUE #358: Can not fetch the package with a insecure protocol from my custom import path
Please see contents below:
```bash
$ gb vendor fetch go.wepiao.com/base_lib/log
skipping insecure protocol: http://go.wepiao.com/base_lib/log?go-get=1
FATAL command "fetch" failed: unable to determine remote metadata protocol
FATAL command "vendor" failed: exit status 1
```

As you can see, It is failed to get the package from our git server, but `go get -insecure go.wepiao.com/base_lib/log` is OK.

I think that gb should support `-insecure ` flag.

### PR DESCRIPTION
**Pull request by davecheney**
Fixes #358

### CODE REVIEW

**Comment by hyper-carrot** [comment]
got it!

**Comment by hyper-carrot** [comment]
Er...I don't think the error message is uniform. 

What about this?

```
// FetchMetadata fetchs the remote metadata for path.
func FetchMetadata(path string, insecure bool) (rc io.ReadCloser, err error) {
        defer func() {
		if err != nil  {
			err = fmt.Errorf("unable to determine remote metadata protocol: %s", err)
		}
        }()
	// try https first
	rc, err = fetchMetadata("https", path)
	if err == nil {
		return
	}
	// try http if supported
	if insecure {
		rc, err = fetchMetadata("http", path)
		return
	} else {
		log.Infof("skipping insecure protocol: %v", "http")
	}
	return
}
```

**Comment by davecheney** [comment]
@hyper-carrot, please feel free to send a PR

**Comment by hyper-carrot** [comment]
@davecheney okok ;)

**Pull request closed without merging**
