### PR TITLE
cmd/gb-vendor/restore: add missing -precaire flag for restore

### PR DESCRIPTION
**Pull request by chilts**

### CODE REVIEW

**Comment by davecheney** [comment]
Not LGTM sorry, alldocs.go is auto generated https://github.com/constabulary/gb/blob/master/cmd/gb/alldocs.go#L2

Please do the following 
```
cd $GOPATH/src/github.com/constabulary/cmd/gb
go install 
go generate
```

**Comment by chilts** [comment]
Ah sorry. Will re-do. Thanks.

**Comment by davecheney** [comment]
@chilts thanks, push a new revision and i'll merge it.

**Comment by chilts** [comment]
I found the place in `cmd/gb-vendor/restore.go` to change, but when I `go generate`, nothing happens to `alldocs.go`. Should it? Or is that step done separately?

(And assuming your above first command is `cd $GOPATH/src/github.com/constabulary/gb/cmd/gb`.)

**Comment by davecheney** [comment]
Yeah, you need to go install .../cmd/gb as the generate command calls gb help with a special flag to dump out the docs.

**Comment by chilts** [comment]
Sorry about that. Re-pushed. Hope I've done it right this time. :) Waiting for tests.

**Comment by chilts** [comment]
Thanks @davecheney.

**Pull request merged**
