### PR TITLE
Cleanup go vet warnings

### PR DESCRIPTION
**Pull request by gliptak**
https://goreportcard.com/report/github.com/constabulary/gb

### CODE REVIEW

**Comment by davecheney** [comment]
Thanks

**Comment by davecheney** [comment]
Sorry, this broke the tests. Please send a new PR and we'll try again

**Comment by gliptak** [comment]
@davecheney The build shows a stall:

https://travis-ci.org/constabulary/gb/jobs/177179333

Would you have a pointer what could cause this?

Thanks

**Comment by davecheney** [comment]
I don't know what the cause is, I'll have to try to find time this weekend to investigate.

**Comment by davecheney** [comment]
I've fixed the build, please send a new PR.

**Pull request merged**
