### PR TITLE
Added SIGINT handling in context

### LINKED ISSUE #436: gb should catch ^C and issue ctx.Destroy
Important to avoid leaving stacks of /tmp/gbNNN directories around.

### PR DESCRIPTION
**Pull request by davidkaya**
Fixes #436 

Not quite sure about the return code though.

### CODE REVIEW

**Comment by davecheney** [comment]
Thanks for taking a look at this. I would like to see the logic move to the command, not context.

**Comment by davidkaya** [comment]
@davecheney Dave? I tried calling it in RunCommand, but it seems it does not get called. Do you know where the problem could be?

**Comment by davecheney** [comment]
@davidkaya this code should not go in gb.Context, there may be more than one context in use per program.

**Comment by davidkaya** [comment]
Yep, I know, but I have tried to put the sigint handling into RunCommand in cmd.go and it does not seem to get called.

**Comment by davidkaya** [comment]
@davecheney I've moved it to command.

**Comment by davecheney** [comment]
I'm really sorry to say this but this is not what I want. I'm very sorry, because I know you are volunteering your time and effort for free. Can we please move this discussion to the issue to talk about the implementation, then do the implementation.

Thanks

**Comment by davidkaya** [comment]
@davecheney Sure, no problem :)

**Comment by davecheney** [comment]
Thanks. FWIW I think each main should have something like

var onExit []func() error

func exit(code int) {
    for _, fn := range onExit {
          fn()
    }
    os.Exit(code)
}

Then replace the usual defers with appends to onExit.

**Comment by davecheney** [comment]
Also, cmd/gb needs to ignore ^C, not hook and exit. See the way it's done in cmd/go

**Comment by davidkaya** [comment]
I will create new PR for the signal handling.

**Pull request closed without merging**
