### PR TITLE
Fix infinite loop and wrong "Separator" issues for windows

### LINKED ISSUE #384: Multiple test failures on Windows
OS: Win7 x64
Go: 1.5.1

Pulling this out of https://github.com/constabulary/gb/pull/377 per request.

```
C:\Users\alan\gopath\src\github.com\constabulary\gb>go test -short github.com/co
nstabulary/gb/...
a
a
b
a
d.v1
c
d.v1
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
notestfiles
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
--- FAIL: TestBuild (0.62s)
        build_test.go:74: ctx.Build(cgomain): want <nil>, got # C:\Go\pkg\tool\w
indows_amd64\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb281314287\cgomain\_c
go -importpath cgomain -- -I C:\Users\alan\AppData\Local\Temp\gb281314287\cgomai
n\_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata\src\cgoma
in main.go: exit status 2
        build_test.go:74: ctx.Build(cgotest): want <nil>, got # C:\Go\pkg\tool\w
indows_amd64\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb997494402\cgotest\_c
go -importpath cgotest -- -I C:\Users\alan\AppData\Local\Temp\gb997494402\cgotes
t\_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata\src\cgote
st basic.go: exit status 2
        build_test.go:74: ctx.Build(cgoonlynotest): want <nil>, got # C:\Go\pkg\
tool\windows_amd64\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb557978884\cgoo
nly\_cgo -importpath cgoonlynotest -- -I C:\Users\alan\AppData\Local\Temp\gb5579
78884\cgoonly\_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testda
ta\src\cgoonlynotest cgoonly.go: exit status 2
        build_test.go:74: ctx.Build(cppmain): want <nil>, got # C:\Go\pkg\tool\w
indows_amd64\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb119974520\cppmain\_c
go -importpath cppmain -- -I C:\Users\alan\AppData\Local\Temp\gb119974520\cppmai
n\_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata\src\cppma
in main.go: exit status 2
a
a
b
a
d.v1
c
d.v1
a
b
--- FAIL: TestPackageBinfile (0.00s)
        package_test.go:68: (b).Binfile(): want C:\Users\alan\gopath\src\github.
com\constabulary\gb\testdata\bin\b, got C:\Users\alan\gopath\src\github.com\cons
tabulary\gb\testdata\bin\b.exe
FAIL
FAIL    github.com/constabulary/gb      1.409s
*** Test killed: ran too long (10m0s).
FAIL    github.com/constabulary/gb/cmd  600.170s
ok      github.com/constabulary/gb/cmd/gb       0.100s
?       github.com/constabulary/gb/cmd/gb-vendor        [no test files]
?       github.com/constabulary/gb/log  [no test files]
ok      github.com/constabulary/gb/vendor       0.245s
```

### PR DESCRIPTION
**Pull request by tianon**
Fixes #384

### CODE REVIEW

**Comment by tianon** [comment]
Ok, updated with a fix for the other Windows-failing test.

https://ci.appveyor.com/project/tianon/gb/build/build-33.appveyor :tada:
(testing on both 64bit and 32bit, full passing tests :dancer:)

**Comment by tianon** [comment]
I think it's still worth discussing whether `a.exe.test` or `a.test.exe` makes more sense, but this at least updates the test to reflect what the compiler's currently doing.

**Comment by tianon** [comment]
Want me to add my AppVeyor stuff here, or in a separate PR? :smile:

**Comment by davecheney** [comment]
Separate PR.

All windows executables need to end in .exe, because that is why we cannot
have nice things.

**Comment by davecheney** [comment]
LGTM. Thanks @tianon

**Pull request merged**
