### PR TITLE
Fix typo in vendor fetch doc

### PR DESCRIPTION
**Pull request by ulfnielsen**
This just kept attracting my eye sorry. "supplie" -> "supplied"

### CODE REVIEW

**Comment by davecheney** [comment]
Please gofmt this change then I will submit it. Thanks.

**Comment by ulfnielsen** [comment]
Done, but kinda strange having to run gofmt on a file coming from go generate and which includes a "do not edit" comment.

**Comment by davecheney** [comment]
Yes, it sucks a bit. If you'd like to track down the two bits of whitespace
in the template, then we won't have to do this extra step.

**Comment by ulfnielsen** [comment]
I've removed the whitespace as well (missed it the first time around) and removed the leading newline in the template strings.

**Comment by davecheney** [comment]
LGTM. Thanks

**Pull request merged**
