### PR TITLE
Update wercker.yml to use "box: golang" and use the updated integration-tests to simplify test running

### PR DESCRIPTION
**Pull request by tianon**
See https://github.com/constabulary/integration-tests/pull/1 for details. :+1:

(This totally enables both `go-sdl2` and `service.v1`! :metal:)

### CODE REVIEW

**Comment by tianon** [comment]
Aww looks like Wercker's build is very unhappy not to have Docker support. :innocent:

**Comment by davecheney** [comment]
This failed 'cos I need to switch to the docker based mode. Two secs.

**Comment by davecheney** [comment]
Boom, land it @tianon

**Comment by davecheney** [comment]
Thanks. you rock.

**Comment by tianon** [comment]
I named the branch `wrecker` in honor of my sad realization today that it's actually `wercker`, which I'd been reading wrong since the first time I saw it.  Personally, I think "wrecker" is a much cooler name for a CI system, since I want it to wreck _all_ my projects. :metal:

Any particular tests you'd like me to work on adding, while I've got a few more cycles this evening? :smile:

**Comment by davecheney** [comment]
Worst. Product. Name. Eva.

**Pull request merged**
