### PR TITLE
add version command

### PR DESCRIPTION
**Pull request by willf**
Wanted to be able to ask the `gb` command what its current version was, but I see no way to do so. This adds a `version` command to do this.

### CODE REVIEW

**Comment by davecheney** [comment]
I;m fine with adding a version command, but I'm sure i'll forget to update that constant. Is there any way to automate this ?

**Comment by willf** [comment]
I added a 'version.sh' script which will modify the version.go file. It's possible to add this as a git hook, but I think you have to do it on your side.

**Comment by freeformz** [comment]
We faced the same problem with tools/godep and just agreed to bump the version with any code changes to master. Yes that sucks BTW.

**Comment by davecheney** [comment]
Thank you for this proposal. Sadly I am not going to merge this at this time.

I do want a version command, but I'm not interested in adding one until it is completely automatic. 

By this I mean, the value reported by gb version should match the tag or revision that gb was built from. I don't think we can do that today with the go tool, and simulating it with a constant would mean releasing from a branch, or a more involved release process involving setting the version to the release version comitting, tagging, then changing it back to some opaque devel version.

At the rate gb is iterating I don't think this overhead is worthwhile. Possibly in the future it will be, maybe when we get to self hosting #14.

**Pull request closed without merging**
